name: Build APK FIX AUTOTOOLS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install full build system
      run: |
        sudo apt update
        sudo apt install -y \
          git zip unzip openjdk-17-jdk \
          python3-pip build-essential \
          autoconf automake libtool \
          libtool-bin m4 pkg-config \
          autoconf-archive

        pip install --upgrade pip
        pip install cython==0.29.36 buildozer

    - name: Build APK
      run: |
        export CI=1
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk