name: Build APK (NO ROOT FIX)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          git zip unzip openjdk-17-jdk \
          python3-pip build-essential \
          autoconf automake libtool pkg-config

        pip install --upgrade pip
        pip install cython==0.29.36 buildozer

    - name: Force non-root build
      run: |
        export HOME=/home/runner
        export CI=1
        export PIP_BREAK_SYSTEM_PACKAGES=1

        mkdir -p $HOME/.buildozer

        buildozer android clean || true
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk