name: Build APK (STABLE FIX)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build APK (NO ANDROID SDK INSTALL)
      run: |
        docker run --rm \
        -v $PWD:/app \
        -w /app \
        kivy/buildozer \
        bash -c "
          pip install --upgrade pip &&
          pip install cython==0.29.36 &&
          buildozer init || true &&
          buildozer android debug
        "

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk